### PR TITLE
fix the error of oom when synthesis and remove the dependency of deepvoice3

### PR DESCRIPTION
**Pull request by azraelkuan**
fix the error of oom when synthesis and remove the dependency of deepvoice3

### CODE REVIEW

**Comment by r9y9** [comment]
As I mentioned in https://github.com/r9y9/wavenet_vocoder/issues/37#issuecomment-384895544, I'm still not sure why OOM happens, but others look nice! I would be happy to accept your PR if you are okay.

**Comment by azraelkuan** [comment]
ok, i will re-test the sample process

**Comment by butterl** [comment]
Using pretrained model and the training npy data, The only GPU run is slow （10-13it/s ） and it gose down to 1-2 it/s and gives OOM message， with @azraelkuan 's  patch， the evaluation speed from my case（6GB GTX1060TI and 12 core CPU） gose to 70-80it/s when changing to torch.set_num_threads(8)，and all OOM disapeared

**Comment by azraelkuan** [comment]
the oom probelm may like this:https://discuss.pytorch.org/t/cuda-memory-continuously-increases-when-net-images-called-in-every-iteration/501/6
in my computer, the speed is like this:
1 cpu 70it/s
2 cpu 85it/s
3 cpu 105it/s
4 cpu almost the same with 3 cpu so i set it default to 4

i am working on the paralle wavenet, may codes are different from the master, so i will make new a branch for PR

**Comment by r9y9** [comment]
Thanks! The link you provided is very helpful. 

> i am working on the paralle wavenet, 

You are going ahead from me :)

**Pull request closed without merging**
