### PR TITLE
Add --preset parameter to evaluate.py.

### PR DESCRIPTION
**Pull request by aleksas**
Used a preset for training. Afterwards when tried to use evaluate.py it was unintuitive/inconvinient to specify hparams in commandline.

### CODE REVIEW

**Comment by r9y9** [comment]
Thanks!

**Comment by aleksas** [comment]
No thank you :) Great job!!!
My results for Lithuanian language: https://aleksas.github.io/wavenet_vocoder_liepa/

**Comment by r9y9** [comment]
Cool! Samples sound a little buzzy, but I think you'll get clearer samples after more training steps.

**Comment by aleksas** [comment]
I think so :) That was after 2000 epochs on 624 utterances from 17 speakers. As I've noticed you recommend running twise the training. In my case the presets were almost identical as for LJSpeach. So, I guess it should work  nicely :)

And how should I run training the second time? train.py with --checkpoint=<path> ? Should path point to ..ema.pth or not? And what does ema stands for?

What do you think about the combination of tacotron-2 with model I'm training? I.e. conditioned on speaker? I mean this one: [Tacotron2: WaveNet-based text-to-speech demo](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb)?..

**Pull request merged**
